style:
  color:
    palette: light
    custom:
      light:
        bg: '#ffffff'
        accent-bg: '#f5f7ff'
        text: '#212121'
        text-light: '#585858'
        border: '#d8dae1'
        accent: '#004d40'
        code: '#795548'
        preformatted: '#444444'
        disabled: '#efefef'
        accent_bg: '#f5f7ff'
        text_light: '#585858'
      dark:
        bg: '#212121'
        accent-bg: '#2b2b2b'
        text: '#dcdcdc'
        text-light: '#ababab'
        border: '#666666'
        accent: '#00bcd4'
        code: '#ea80fc'
        preformatted: '#cccccc'
        disabled: '#111111'
        accent_bg: '#2b2b2b'
        text_light: '#ababab'
  custom:
    css: null
    js: null
partials:
  navigation:
    where: header
  metadata:
    where: header
  footer:
    theme_attribution:
      toggle: false
    attribution:
      content: null
media:
  favicon:
    file: {  }
  featured_image:
    file: 'theme://assets/image/preview-image.png'
