enabled: true
production-mode: true
grid-size: grid-lg
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
blog-page: /blog
spectre:
  exp: false
  icons: false
custom_logo:
  user/themes/quark/images/logo/adijaya.id.png:
    name: adijaya.id.png
    full_path: adijaya.id.png
    type: image/png
    size: 12444
    path: user/themes/quark/images/logo/adijaya.id.png
custom_logo_mobile:
  user/themes/quark/images/logo/adijaya.id.png:
    name: adijaya.id.png
    full_path: adijaya.id.png
    type: image/png
    size: 12444
    path: user/themes/quark/images/logo/adijaya.id.png
